name: Print Hello World on Push to Master
on:
  push:
    branches:
      - Master
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, world!"
