name: CI Serevr
on:
  push:
    branches:
      - Master
jobs:
  Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Changes Detected
        run: |
          echo "Changes has be detected on Master Branch"
          echo "The most recent commit message is: ${GITHUB_SHA}"
  Time:
    runs-on: ubuntu-latest
    steps:
      - name: Time
        run: |
          echo "Commit Time  ---> "
          date