name: CI Serevr
on:
  push:
    branches:
      - Development
jobs:
  Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Changes Detected
        run: |
          echo "Changes has be detected on Development Branch"
          echo "The most recent commit message is: ${GITHUB_SHA}"
      - name: Print Commit Time
        run: |
          echo "Commit Time  ---> "
          date