name: CI Serevr
on:
  push:
    branches:
      - Master
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Changes Detected
        run: |
        echo "Changes has be detected on Master Branch"
        echo "The most recent commit message is: ${GITHUB_SHA}"
